---
title: "Homework 1"
output: pdf_document
---

```{r, echo=FALSE, eval=TRUE, message=FALSE}
library(tidyverse)
library(latex2exp)
theme_set(theme_bw())
```

1. Given the following demand function for a computer, $Q=100-0.4p+1.2p_a+3Y$, and $p=20$, $p_a=10$, and $Y=50$, where $p$ is the good's own price, $p_a$ is the price of good $a$, and $Y$ is income:

a. Calculate elasticity of demand. Explain in one sentence what your answer means.

$$
\frac{\partial Q}{\partial p} = -0.4p
$$$$
\varepsilon = \frac{\partial Q}{\partial p} \frac{p}{Q}
$$$$
\varepsilon = -0.4p \frac{p}{100-0.4p+1.2p_a+3Y} = \frac{2p}{2p - 15Y - 6 p_a - 500}
$$$$
\varepsilon = \frac{2(20)}{2(20) - 15(100) - 6 (10) - 500} = \frac{40}{40 - 1500 - 60 - 500}
$$$$
\varepsilon = -\frac{40}{2020} = -\frac{2}{101} \approx -0.01980198020
$$

The sensitivity of demand quantity to change in price. Specifically percentage change.

From now on I will be shorthanding this calculation, I believe I have demonstrated I know how to calculate elasticity.

b. Calculate cross-price elasticity. Explain in one sentence what your answer means.

$$
\varepsilon_a = \frac{\partial Q}{\partial p_a} \frac{p_a}{Q}
= \frac{3}{101} \approx 0.02970297030
$$

The sensitivity of demand quantity to change in the price of an alternative good.

c. Calculate income elasticity. Explain in one sentence what your answer means.

$$
\xi = \frac{\partial Q}{\partial Y} \frac{Y}{Q}
= \frac{75}{101} \approx 0.7425742574
$$

The sensitivity of demand quantity to change in income.


2. a. Given the following demand and supply functions, calculate the change in price paid by consumers, $\Delta p$, following the assessment of a specific tax, $\tau = \$15.50$ (starting from $\tau = \$0.00$). Assume the market is in equilibrium to begin with.

$$
Q_D = 30,000 - 15p
$$$$
Q_S = 5,000 + 35p
$$

$$
\left[
\begin{array}{cc}
1 & 12 \\
1 & -35
\end{array}
\right]
\left[
\begin{array}{c}
Q^* \\
p^*
\end{array}
\right] =
\left[
\begin{array}{c}
30,000 \\
5,000
\end{array}
\right]
$$$$
\left[
\begin{array}{c}
Q^* \\
p^*
\end{array}
\right] =
\left[
\begin{array}{c}
22,500 \\
500
\end{array}
\right]
$$$$
\varepsilon = \frac{\partial Q_D}{\partial p} \frac{p}{Q_D} = 1 + \frac{2000}{p^* - 2000} = -\frac{1}{3}
$$$$
\eta = \frac{\partial Q_S}{\partial p} \frac{p}{Q_S} = 1 + \frac{1000}{7p^* - 1000} = \frac{7}{9}
$$$$
\Delta p = \frac{\eta}{\eta-\varepsilon}\Delta \tau = \frac{7}{10} \$15.5 = \$10.85
$$$$
p^{**} = p^*+\Delta p = \$510.85
$$$$
Q^{**} = 30,000 - 15 p^{**} = 22,337.25
$$

b. How much will be collected in tax revenue?

$$
T=Q^{**}\tau = 22,337.25\cdot\$15.5 = \$346,227.375
$$

c. How much of this amount will be paid by consumers?

$$
T_\text{consumer}=Q^{**}\Delta p = 22,337.25\cdot\$10.85 = \$242,359.1625
$$

3. ...

a. Calculate the change in price paid by the consumer following the assessment of a specific
tax of $\tau = \$0.50$.

$$
\Delta p = \frac{1.5}{1.5-(-0.5)} \cdot \$0.50 = \$1.50
$$

b. ...

The ad valorem tax is a variable tax rate based on price, such that if the price is zero, then the tax is zero. This fixes the point on the demand curve at zero + the constant demand. However, at higher prices the tax increases, giving a wider gap between the true demand curve and the taxed one. This effect happens all along the line all the way up to the $Q=0$ intercept. This causes the graph to appear to "rotate" as it were.

4. ...

$$
\eta = \frac{\delta Q}{\delta p} \frac{p}{Q} = \frac{1}{6}
$$